### ISSUE TITLE
conflict on function names with Flux.jl

### ISSUE THREAD

**Issue by foldfelis** [JuliaML/MLUtils.jl#71]
```sh
WARNING: Method definition rpad(AbstractArray{T, 1} where T, Integer, Any) in module MLUtils at /home/admin/.julia/packages/MLUtils/OojOS/src/utils.jl:384 overwritten in module Flux at /home/admin/.julia/packages/Flux/7nTyc/src/utils.jl:610.
  ** incremental compilation may be fatally broken for this module **
```

**Comment by darsnack** [comment]
I believe this is already fixed on the dev branch. We just need to make a release. @CarloLucibello I think we are okay to do that?

**Comment by CarloLucibello** [comment]
I don't see this issue doing `using Flux, MLUtils` on last tagged version, but I tagged a new release in any case. @foldfelis let us know if the issue persists.

**Comment by foldfelis** [comment]
Hi @CarloLucibello , the problem is solved by update to v0.2.2

**Comment by foldfelis** [comment]
Sorry, I forgot to recompile, it is not solved. Please take a look at [this](https://github.com/SciML/NeuralOperators.jl/blob/training_process/example/FlowOverCircle/src/FlowOverCircle.jl)

**Comment by foldfelis** [comment]
The problem is solved by using Flux v0.13 with MLUtils v0.2.2
